_core:
  default_config_hash: ViXe1Mhsdfc0AY1y-5R7vwxUoVItsnRfbQbQYzQGEEs
langcode: sk
api_key: 29ffa3a59b6c20e34ce042d42af856fb-us20
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: false
connected_id: null
connected_paths: null
webhook_hash: afee7d6edf8d875bab2a69e75bb68797
